#!/usr/bin/env bash
# Change your home IP address to 127.0.0.2
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
